networks:
  proxy-services-net:
    name: proxy-services-net

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC1.1
    container_name: mealie
    deploy:
      resources:
        limits:
          memory: 1000M
    environment:
      - ALLOW_SIGNUP=true
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=${BASE_URL}
    volumes:
      - ${PATH_SERVICES}/mealie/config:/app/data/
    ports:
      - 9925:9000
    networks:
      - proxy-services-net
    restart: unless-stopped